### ISSUE TITLE
Stakerd startup failure while handling CONFIRMED_ON_BTC transactions

### ISSUE THREAD

**Issue by vic-dayou** [babylonchain/btc-staker#131]
## Context:

Stakerd checks for pending transactions in the database upon startup. If it encounters a transaction with the status `TransactionState_CONFIRMED_ON_BTC`, it attempts to build a babylon delegate transaction. However, it seems to run into an issue when it tries to fetch transaction details using the `getrawtransaction` method. 

According to the [Bitcoin Developer Reference for getrawtransaction](https://developer.bitcoin.org/reference/rpc/getrawtransaction.html), by default, this function only works for mempool transactions. Therefore, once a transaction has been confirmed, it throws the error `{"result":null,"error":{"code":-5,"message":"No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions."},"id":"1"}`. This behavior eventually causes a Stakerd startup failure.

**Comment by vic-dayou** [comment]
log:
`service injective.evm.v1beta1.Msg does not have cosmos.msg.v1.service proto annotation
time="2024-04-12T10:59:44+08:00" level=info msg="Starting StakerApp"
time="2024-04-12T10:59:44+08:00" level=info msg="Connecting to node backend: bitcoind"
time="2024-04-12T10:59:44+08:00" level=info msg="Successfully started Prometheus metrics server at 127.0.0.1:2112"
time="2024-04-12T11:00:01+08:00" level=info msg="Successfully connected to node backend: bitcoind"
time="2024-04-12T11:00:01+08:00" level=info msg="Initial btc best block height is: 190931"
time="2024-04-12T11:22:32+08:00" level=error msg="Shutting down because error in main method: error starting staker: unable to query for txid 511b4150347f44ba85fe276b875dc4b684735a98cdd7870e8f709945b1f59fc5: -5: No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions."
time="2024-04-12T11:22:32+08:00" level=info msg="Closing database..."
time="2024-04-12T11:22:32+08:00" level=info msg="Database closed"
time="2024-04-12T11:22:32+08:00" level=info msg="Shutdown complete"
error starting staker: unable to query for txid 511b4150347f44ba85fe276b875dc4b684735a98cdd7870e8f709945b1f59fc5: -5: No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions.
Exiting.
`

**Comment by KonradStaniec** [comment]
Hey thanks for the issue, this is known problem in our docs. The bitcoin node which staker is connected to must be run with `-txindex` option. So the way to work around the problem is to:
1. re-sync bitcoind node with `-txindex` option
2. re-start stakerd daemon

**Comment by vic-dayou** [comment]
Yes, you are right, but I think it is necessary to update the document. I followed the instructions of the document exactly, so I think it is necessary to update the document and add the startup parameter `-txindex`
